Repository inovex/elements, pull requests merged in 2022-05, with the labels that each got.

#586 fix(elements|ino-autocomplete): fix wrong menu positioning if helper text exists
  packages/elements/src/components/ino-autocomplete/ino-autocomplete.scss
  packages/storybook/src/stories/ino-autocomplete/ino-autocomplete.stories.ts
Labels: small PR

#580 fix(storybook): stories not being sorted correctly
  packages/storybook/package.json
  yarn.lock
Labels: small PR

#581 ci: remove security pipeline
  .github/workflows/security.yml
Labels: small PR

#567 docs: update component development docs
  packages/storybook/src/stories/docs/contributing/04-developing-components.stories.mdx
Labels: small PR

#579 build(elements): delete timestamp from json docs
  packages/elements/json-docs-output-target.ts
  packages/elements/stencil.config.ts
  packages/storybook/elements-stencil-docs.json
Labels: small PR

#594 refactor(storybook|ino-radio-group): reformat stories
  packages/storybook/src/stories/ino-radio-group/ino-radio-group.stories.ts
Labels: small PR

#588 refactor(storybook|ino-form-row): reformat stories
  packages/storybook/elements-stencil-docs.json
  packages/storybook/src/stories/ino-form-row/ino-form-row.stories.ts
Labels: small PR

#556 refactor(elements|ino-icon): rename icon `request` to `share`
  packages/elements/src/assets/ino-icon/share.svg
  packages/elements/src/components/ino-icon/icons.js
Labels: breaking change

#571 style(elements|ino-button): update styling
  packages/elements-angular/elements/src/directives/proxies.ts
  packages/elements/src/components.d.ts
  packages/elements/src/components/ino-button/ino-button.e2e.ts
  packages/elements/src/components/ino-button/ino-button.scss
  packages/elements/src/components/ino-button/ino-button.tsx
  packages/elements/src/components/ino-button/readme.md
  packages/elements/src/components/ino-spinner/ino-spinner.scss
  packages/elements/src/components/types.ts
  packages/storybook/elements-stencil-docs.json
  packages/storybook/src/stories/ino-button/ino-button.scss
  packages/storybook/src/stories/ino-button/ino-button.stories.ts
Labels: breaking change, ready for next major

#537 refactor(elements-react): use stencils react-output-target
  packages/elements-react/.eslintrc.js
  packages/elements-react/package.json
  packages/elements-react/scripts/postbuild.js
  packages/elements-react/scripts/reactwrapper.js
  packages/elements-react/src/components/index.ts
  packages/elements-react/src/components/react-component-lib/createComponent.tsx
  packages/elements-react/src/components/react-component-lib/createOverlayComponent.tsx
  packages/elements-react/src/components/react-component-lib/index.ts
  packages/elements-react/src/components/react-component-lib/interfaces.ts
  packages/elements-react/src/components/react-component-lib/utils/attachProps.ts
  packages/elements-react/src/components/react-component-lib/utils/case.ts
  packages/elements-react/src/components/react-component-lib/utils/dev.ts
  packages/elements-react/src/components/react-component-lib/utils/index.tsx
  packages/elements-react/src/index.ts
  packages/elements-react/tsconfig.json
  packages/elements-vue/src/proxies.ts
  packages/elements/package.json
  packages/elements/stencil.config.ts
  packages/storybook/elements-stencil-docs.json
  packages/storybook/src/stories/docs/framework-integration/react-instructions.stories.mdx
  yarn.lock
Labels: breaking change, ready for next major
